"""Collection store!: Available collections"""

COLLECTIONS = {
    "stable": [
        "iceK",
        "iceWires",
        "iceIO",
        "iceGates",
        "iceMux",
        "iceCoders",
        "iceFF",
        "iceRegs",
        "iceSRegs",
    ],
    "dev": [
        "iceBoards",
        "iceComp",
        "iceArith",
        "iceCounter",
        "iceSignals",
        "icePLL",
        "iceLEDOscope",
        "iceLEDs",
        "iceHeart",
        "iceInputs",
        "iceRok",
        "iceMachines",
        "iceSerial",
        "iceMem",
        "iceMeassure",
        "iceStack",
        "iceFlash",
        "iceBus",
        "iceLCD",
        "iceSynth-collection",
        "Collection-stdio",
        "LOVE-FPGA-Collection",
        "Collection-Jedi",
        "CT11-collection",
        "collection-generic",
        "collection-logic",
        "Icestudio-ArithmeticBlocks",
        "icebreaker-collection",
        "icecrystal",
        "ice-chips-verilog",
    ],
}
