# ...

name: Build/Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                python-version: [3.9]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  make deps

            - name: Run tox
              run: |
                  make tox
